### ISSUE TITLE
Indigo 2022.2 No Content-Type error

### ISSUE THREAD

**Issue by Ghawken** [FlyingDiver/Indigo-GeoFence#2]
https://github.com/FlyingDiver/Indigo-GeoFence/blob/cac20c321052c6fa5c517954878605f24912ec92/GeoFence.indigoPlugin/Contents/Server%20plugin/plugin.py#L266

Seems new Sanic Webserver has updated all headers to lowercase (believe is now a standard somewhere..)

“content-type” fixes, as does changing “User-Agent” to “user-agent”

Thanks

**Comment by FlyingDiver** [comment]
Fixed in 2022.1.2, I hope.

**Comment by FlyingDiver** [comment]
Try:  https://github.com/FlyingDiver/Indigo-GeoFence/releases/tag/2022.1.2
