### ISSUE TITLE
2022.1.2 Change in CFBundleIdentifier means no (current/old) devices are recognised.

### ISSUE THREAD

**Issue by Ghawken** [FlyingDiver/Indigo-GeoFence#3]
https://github.com/FlyingDiver/Indigo-GeoFence/blob/bbc27dab7b96705b1239d994c672605cbc2d42c0/GeoFence.indigoPlugin/Contents/Info.plist#L12

Need to add the dot back in… eg. indigo.plugin

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-GeoFence/releases/tag/2022.1.3
