### ISSUE TITLE
Locative/581 (support for older phone)

### ISSUE THREAD

**Issue by whmoorejr** [FlyingDiver/Indigo-GeoFence#5]
With the change of FFM and then the loss of Life360, I'm on the hunt for a new platform to perform geospacial automation and track my horde of kids.  Problem, 4 of them are using older iPhone 6s that are maxed at iOS 12.5.7 and therefore run an older version of Locative.

The "Send Test-Request" is successful.... but I'm getting errors on entry and exits of geofences.  To make it even more fun, the older version doensn't have an option to (Trigger "Enter" Event) or exit.  So, to test, I'm driving around town with a pocket full of iPhones.

Attached is the debug log of an entry and exit by one of the iPhone 6s.  (Note: all my iPhones get bumped up a year when they appear in the log... The 6s shows up as a 7, the 7 shows up as an 8.  The X shows up as an 11 and the 13s show up as 14s.

Side thought.... I'm also looking at the "OwnTracks" app.  I can get your plugin to see it, but the format I guess is off.  That app is a (IMO) better alternative to Life360.  It does geofences (Regions) and you can track friends, but there is also a decent API publicly available for it.  I've only tinkered with that app, not worth it if I can't get it automated.

Last side comment.  I can't think of a case use, but I was trying to create a iOS Shortcut to populate as a Custom device in your plugin.  I couldn't get the setting right.... but I think I was close.  <- Just something to mess around with.
[Geobeacon Debug.txt](https://github.com/FlyingDiver/Indigo-GeoFence/files/13896399/Geobeacon.Debug.txt)

**Comment by FlyingDiver** [comment]
Looks like the older versions of Locative do not include a content-type header.  I'll need to look at the code and see how critical that is.  There's error checking in there now to abort if it's not there, but I don't know if there's a work-around.

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-GeoFence/releases/tag/2022.1.5

**Comment by whmoorejr** [comment]
Thankyou.  I’ll know how it’s going in a couple hours when the kids get out of school and the notifications start rolling in. 

Respectfully,

Bill Moore
***@***.***
832-294-3096

**Comment by whmoorejr** [comment]
Closer, but error 'key body_params not found in dict'  Debug log attached.


[Debug Geofence body_params.txt](https://github.com/FlyingDiver/Indigo-GeoFence/files/13908682/Debug.Geofence.body_params.txt)

**Comment by FlyingDiver** [comment]
Turn on debug logging.  I need to see the actual content you're getting.

**Comment by whmoorejr** [comment]
This?
Here is an exit and enter log:


```
 GeoFence Debug                  reflector_handler: se.furtenbach.indigo.plugin.beacon : (dict)
     file_path : (list)
     headers : (dict)
          accept : */* (string)
          accept-encoding : br, gzip, deflate (string)
          accept-language : en-us (string)
          connection : close (string)
          host : localhost:14876 (string)
          user-agent : Locative/581 CFNetwork/978.0.7 Darwin/18.7.0 (string)
          x-forwarded-for : 174.251.242.2 (string)
          x-forwarded-host : redact.indigodomo.net (string)
          x-forwarded-server : somereflectorhere.indigodomo.net (string)
     incoming_request_method : GET (string)
     url_query_args : (dict)
          api_key : redact (string)
          device : C6B2F9D7-F43F-45A1-A7F0-8484C2ADB0E4 (string)
          device_model : iPhone7,2 (string)
          device_type : iOS (string)
          id : ISL (string)
          latitude : 29.4948942979611 (string)
          longitude : -95.17218354777557 (string)
          timestamp : 1705006937.737016 (string)
          trigger : exit (string)
   GeoFence Debug                  No content-type header found
   GeoFence Debug                  user-agent: Locative/581 CFNetwork/978.0.7 Darwin/18.7.0, content-type: None
   GeoFence Debug                  Recognised Locative/Geofancy
   GeoFence Warning                Recognised Locative/Geofancy, error parsing data: 'key body_params not found in dict'
   GeoFence Debug                  reflector_handler: se.furtenbach.indigo.plugin.beacon : (dict)
     file_path : (list)
     headers : (dict)
          accept : */* (string)
          accept-encoding : br, gzip, deflate (string)
          accept-language : en-us (string)
          connection : close (string)
          host : localhost:14876 (string)
          user-agent : Locative/581 CFNetwork/978.0.7 Darwin/18.7.0 (string)
          x-forwarded-for : 174.251.242.2 (string)
          x-forwarded-host : redact.indigodomo.net (string)
          x-forwarded-server : somereflectorhere.indigodomo.net (string)
     incoming_request_method : GET (string)
     url_query_args : (dict)
          api_key : redact (string)
          device : C6B2F9D7-F43F-45A1-A7F0-8484C2ADB0E4 (string)
          device_model : iPhone7,2 (string)
          device_type : iOS (string)
          id : ISL (string)
          latitude : 29.4948942979611 (string)
          longitude : -95.17218354777557 (string)
          timestamp : 1705006940.276222 (string)
          trigger : enter (string)
   GeoFence Debug                  No content-type header found
   GeoFence Debug                  user-agent: Locative/581 CFNetwork/978.0.7 Darwin/18.7.0, content-type: None
   GeoFence Debug                  Recognised Locative/Geofancy
   GeoFence Warning                Recognised Locative/Geofancy, error parsing data: 'key body_params not found in dict'
```

**Comment by FlyingDiver** [comment]
Hmm.  That old version is doing an HTTP GET instead of the HTTP PUT that the newer versions do.  There's no config options in that version to change it?

That's going to be more work.

Can you do the same thing for a current version so I can be sure I have that one correct?

**Comment by whmoorejr** [comment]
Interesting…. global settings was set to “PUT”  individual fence set to “GET”.  Clicking the “GET” allowed me to change it to “PUT”.  Let me walk to the end of the neighborhood to trigger an event and I’ll update.

**Comment by whmoorejr** [comment]
I'm golden.  You can close this one out.  I have all 3 of the older iphones reporting in now.  Thank you much and sorry I missed the individual GET/POST option.  

The older version is a PITA.  Menu text is white on a white background (so I have to guess where the "save" text is).  For a location, there is no option to trigger an event.  So for every fence for every phone, I have to physically go to that location while looking at indigo logs from another phone, go home, find the new device and save it with a name.

**Comment by FlyingDiver** [comment]
Can you check to see if they work with the released plugin, not the pre-release?

**Comment by whmoorejr** [comment]
Holly crap I'm so sorry.  Yes, I can confirm that the older phones are working with the 2022.1.4 version.
